### ISSUE TITLE
Add higher es version presets to lower one

### ISSUE THREAD

**Issue by fisker** [mysticatea/eslint-plugin-es#23]
Lower version preset like `no-es5` should include all higher version presets, for easier use.

Currently, if I want disable `es5` syntax, I have to do

```js
{
      extends: [
        'plugin:es/no-2020',
        'plugin:es/no-2019',
        'plugin:es/no-2018',
        'plugin:es/no-2017',
        'plugin:es/no-2016',
        'plugin:es/no-2015',
        'plugin:es/no-5',
      ],
}
```

seems silly, and if someday this plugin add ~`no-2020`~(Update: we already has `no-2020`, but missing on website https://eslint-plugin-es.mysticatea.dev/#presets) `no-2021`, and I didn't update my config, ~`2020`~`2021` syntax will sneak in.

I suggest we include `no-2015` in `no-5`, include `no-2016` in `no-2015`, ..., so to disable `es5`, I can simply just `extends: ['no-5']`, for someone only want disable `2018`, I suggest new preset `no-{version}-only`, like `no-2018-only`.

This will be a breaking change, if you don't want that, we can support this by adding some presets like `no-5-above`, `no-2015-above`.

**Comment by mysticatea** [comment]
Thank you for your proposition.

Sounds reasonable, but we should consider a trade-off.

Currently, I do the following steps to release this plugin:

1. When new language features arrived at Stage 4 and ESTree AST spec updated, I add the rule for the language feature.
1. When ES20xx arrived at feature freeze, I add the preset `no-20xx with the new rules.

I can release this plugin with a minor version up for both cases. But, If we adopt this proposition, the latter is going to require a major version up because it should update existing presets as well. So this plugin is going to be major released more frequently.

**Comment by edg2s** [comment]
+1 to the original proposal. If I am maintaining an ES5 project, the reality is that whenever a new version of ES comes out I need new rules. If that requires major releases then that is just a reflection of reality.

**Comment by astorije** [comment]
Personally, I would prefer a breaking change rather than forgetting to add the new preset on the new year. I think it's a reasonable trade-off to be on the safe side.
I think it's unlikely to desire excluding all features from ES2017 + ES2018 + ES2019 but somehow want all ES2020 features. I would expect this to be an accident.

If not, a new set of presets like the @fisker mentioned, e.g. `no-2018-and-up` would be acceptable, and you could specify in the README that those are safer but subject to breaking changes in minor bumps.

**Comment by mysticatea** [comment]
I have added `plugin:es/restrict-to-esXXXX` configs in 4.0.0 for this purpose. Thank you.
